### ISSUE TITLE
Cannot make it work, repeatedly opening form

### ISSUE THREAD

**Issue by maurocasas** [vinkla/shield#19]
Hello vinkla (and everyone)!

I'm trying to use your package to protect my Laravel Horizon dashboard, using the middlware `shield`, without extra params.

I have updated my .env with hashed settings for both username and password, but the prompt keeps popping up in a loop and cannot access the dashboard.

Am I missing anything?

**Comment by maurocasas** [comment]
I don't really know what I did, but it's working now. I just ran `config:clear` and it all suddenly worked :shrug:

**Comment by brendon** [comment]
I'm having a similar issue. Digging into your code and doing some `var_dump` I've realised that it's never passing in `$users` on `Shield` `__construct`.

Digging deeper, the `register()` method on `ShieldServiceProvider` never seems to be called.

I'm using version 6 of `laravel-shield` because I'm working on a Laravel 7.x project that will eventually be upgraded.

I've tried `php artisan config:clear` to no avail. Any pointers?

**Comment by brendon** [comment]
I've confirmed that the config exists:

```
> config('shield.users')
= [
    "myuser" => [
      "$2y$10$iQFip2A1Nc7KuhBs3.tlKuNGGt10.WumZa3mKR1xxhF7fneJikCNa",
      "$2y$10$nMkz/uRquG3OrrOCc6muG.OP/xdlxi1ec3ZusRlZXNkYoQBUdf/vy",
    ],
  ]
```

**Comment by brendon** [comment]
Manually adding `Vinkla\Shield\ShieldServiceProvider::class,` to `config/app.php` makes it work. I wonder why composer isn't autoloading it? I've run `composer dump-autoload` and I see `vinkla/shield` there :)

**Comment by brendon** [comment]
Hope this helps others. We have our app set up in a Podman pod using php-fpm and an `EmptyDir` mapped to `/bootstrap/cache`. It seems that this isn't ephemeral and survives a reboot. Also, `php artisan config:clear` doesn't work because the cache directory on the local machine isn't the same one that's on the pod container. Once the `/bootstrap/cache` directory was cleared the problem went away :)
